spring:
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        jdbc:
          batch_size: 50
        format_sql: true
        show_sql: true
        order_updates: true
  datasource:
    url: jdbc:mysql://localhost:22306/jungleDB
    username: root
    password: 0000
    driver-class-name: com.mysql.cj.jdbc.Driver